config/routes.rb
Rails.application.routes.draw do
  get 'authors/index'
  devise_for :users
  root 'pages#home'

  # get '/books', to: 'books#index'
  resources :books
  resources :authors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, as: :author

  validates :name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, polymorphic: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, polymorphic: true

  validates :body, presence: true, length: { minimum: 1, maximum: 120 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, as: :author

  validates :username, presence: true,
                       uniqueness: true,
                       length: { minimum: 3, maximum: 15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:username, :email, :password)
    end

    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username, :email)
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index; end

  def new
    @authors = Author.all
    @book = Book.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/books/new.html.erb
<div class="container">
  <h2>Add a new book</h2>
  <%= form_with model: @book do |form| %>
    <div class="field">
      <%= form.label :title, class: 'label' %>
      <%= form.text_field :title, autofocus: true, class: 'input' %>
    </div>
    <div class="field">
      <%= form.label :author, class: 'label' %>
      <%= form.select :author_id, @authors.all.collect {|a| [ a.name, a.id ] } %>
      <%= link_to 'Haven\'t found the author name? try adding to the library too!',
                    new_author_path(return_to: new_book_path),
                    class: 'book_form link'
          %>
    </div>
    <div class="field">
      <%= form.label :release_date, class: 'label' %>
      <div class="data-select">
        <%= form.date_select :release_date,
                                autofocus: true,
                                html: { class: 'select' },
                                start_year: Date.today.year - 100,
                                end_year: Date.today.year %>
      </div>
    </div>
    <div class="actions">
      <%= form.submit "Submit", class: 'button' %>
    </div>
    <p><%= @test %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateYourBoox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= stylesheet_link_tag 'pages/home', media: 'all' %>
<div class='home'>
  <% if current_user %>
    <%= render "pages/partials/logged" %>
  <% else %>
    <%= render "pages/partials/unlogged" %>
  <% end %>
</div>

app/views/pages/partials/_logged.html.erb
<div class='home__logged'>
  <h2 class='home__title'><%= current_user.username %></h2>
  <%= button_to 'Sign out', destroy_user_session_path, method: :delete, form_class: 'home__form-button' %>
  <div class='home__logged-actions'>
    <%= link_to 'Create new book', new_book_path %>
    <%= link_to 'List all books', books_path %>
  </div>
</div>

app/views/pages/partials/_unlogged.html.erb
<h1 class='home__title'>Home</h1>
<div class='home__unlogged'>
  <%= button_to 'Sign up', new_user_registration_path, method: :get %>
  <%= button_to 'Sign in', new_user_session_path, method: :get %>
</div>